export const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/pfAZP7JvTTxqgq7n6A1OYgkAdEW.jpg',
      id: 894205,
      title: 'Werewolf by Night',
      original_language: 'en',
      original_title: 'Werewolf by Night',
      overview:
        'On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple following the death of their leader. In a strange and macabre memorial to the leader’s life, the attendees are thrust into a mysterious and deadly competition for a powerful relic—a hunt that will ultimately bring them face to face with a dangerous monster.',
      poster_path: '/1n2q0Y1pX8PkQh9imqGbNH7Bw4q.jpg',
      media_type: 'movie',
      genre_ids: [28, 14, 27, 10770],
      popularity: 1401.396,
      release_date: '2022-09-25',
      video: false,
      vote_average: 7.3,
      vote_count: 403,
    },
    {
      adult: false,
      backdrop_path: '/83oeqwN64WtafGoITvsOzjKIQaM.jpg',
      id: 718930,
      title: 'Bullet Train',
      original_language: 'en',
      original_title: 'Bullet Train',
      overview:
        "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
      poster_path: '/tVxDe01Zy3kZqaZRNiXFGDICdZk.jpg',
      media_type: 'movie',
      genre_ids: [28, 35, 53],
      popularity: 3159.647,
      release_date: '2022-07-03',
      video: false,
      vote_average: 7.508,
      vote_count: 1754,
    },
    {
      adult: false,
      backdrop_path: '/aTovumsNlDjof7YVoU5nW2RHaYn.jpg',
      id: 616820,
      title: 'Halloween Ends',
      original_language: 'en',
      original_title: 'Halloween Ends',
      overview:
        'Four years after the events of Halloween in 2018, Laurie has decided to liberate herself from fear and rage and embrace life. But when a young man is accused of killing a boy he was babysitting, it ignites a cascade of violence and terror that will force Laurie to finally confront the evil she can’t control, once and for all.',
      poster_path: '/xHLwNxk7Kgpatru7advnbnBGtgf.jpg',
      media_type: 'movie',
      genre_ids: [27, 53],
      popularity: 1416.549,
      release_date: '2022-10-12',
      video: false,
      vote_average: 7.026,
      vote_count: 234,
    },
    {
      adult: false,
      backdrop_path: '/iS9U3VHpPEjTWnwmW56CrBlpgLj.jpg',
      id: 642885,
      title: 'Hocus Pocus 2',
      original_language: 'en',
      original_title: 'Hocus Pocus 2',
      overview:
        'It’s been 29 years since someone lit the Black Flame Candle and resurrected the 17th-century sisters, and they are looking for revenge. Now it is up to three high-school students to stop the ravenous witches from wreaking a new kind of havoc on Salem before dawn on All Hallow’s Eve.',
      poster_path: '/7ze7YNmUaX81ufctGqt0AgHxRtL.jpg',
      media_type: 'movie',
      genre_ids: [14, 35, 10751],
      popularity: 3419.493,
      release_date: '2022-09-27',
      video: false,
      vote_average: 7.7,
      vote_count: 721,
    },
    {
      adult: false,
      backdrop_path: '/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg',
      id: 616037,
      title: 'Thor: Love and Thunder',
      original_language: 'en',
      original_title: 'Thor: Love and Thunder',
      overview:
        'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
      poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
      media_type: 'movie',
      genre_ids: [14, 28, 35],
      popularity: 1551.821,
      release_date: '2022-07-06',
      video: false,
      vote_average: 6.739,
      vote_count: 4209,
    },
    {
      adult: false,
      backdrop_path: '/3r3tZgKTw1554hcFoUfydLHE38w.jpg',
      id: 338947,
      title: 'Hellraiser',
      original_language: 'en',
      original_title: 'Hellraiser',
      overview:
        'A young woman struggling with addiction comes into possession of an ancient puzzle box, unaware that its purpose is to summon the Cenobites, a group of sadistic supernatural beings from another dimension.',
      poster_path: '/f9ZAIUxTTk23vo1BC9Ur1Rx5c2E.jpg',
      media_type: 'movie',
      genre_ids: [27, 9648],
      popularity: 153.497,
      release_date: '2022-09-28',
      video: false,
      vote_average: 6.531,
      vote_count: 195,
    },
    {
      adult: false,
      backdrop_path: '/iHc14vucwUMl6WuvQa4iPfoEdy9.jpg',
      id: 799546,
      title: 'Luckiest Girl Alive',
      original_language: 'en',
      original_title: 'Luckiest Girl Alive',
      overview:
        'A successful woman in New York City finds her life upended when she is forced to confront a dark truth that threatens to unravel her meticulously crafted life.',
      poster_path: '/e0vrbTmTf2ZcW5CIS9qJ8FDbsU9.jpg',
      media_type: 'movie',
      genre_ids: [18, 53, 9648],
      popularity: 461.692,
      release_date: '2022-09-30',
      video: false,
      vote_average: 6.716,
      vote_count: 227,
    },
    {
      adult: false,
      backdrop_path: '/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg',
      id: 361743,
      title: 'Top Gun: Maverick',
      original_language: 'en',
      original_title: 'Top Gun: Maverick',
      overview:
        'After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.',
      poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
      media_type: 'movie',
      genre_ids: [28, 18],
      popularity: 1165.523,
      release_date: '2022-05-24',
      video: false,
      vote_average: 8.354,
      vote_count: 4285,
    },
    {
      adult: false,
      backdrop_path: '/508Ft4l33taZHHN0Ln4TW6XsLim.jpg',
      id: 301502,
      title: 'Blonde',
      original_language: 'en',
      original_title: 'Blonde',
      overview:
        'From her volatile childhood as Norma Jeane, through her rise to stardom and romantic entanglements, this reimagined fictional portrait of Hollywood legend Marilyn Monroe blurs the lines of fact and fiction to explore the widening split between her public and private selves.',
      poster_path: '/jOgbnL5FB30pprEjZaY1E1iPtPM.jpg',
      media_type: 'movie',
      genre_ids: [18],
      popularity: 473.152,
      release_date: '2022-09-16',
      video: false,
      vote_average: 6.514,
      vote_count: 554,
    },
    {
      adult: false,
      backdrop_path: '/zgMjGYxVKwUKvl5UdT9jNkiNyCe.jpg',
      id: 1024530,
      title: 'Grimcutty',
      original_language: 'en',
      original_title: 'Grimcutty',
      overview:
        'A suburban teen girl and her little brother must stop a terrifying internet meme brought to life by the hysteria of their parents.',
      poster_path: '/qvg75YJMfbHeDNirUrrgBMQImRn.jpg',
      media_type: 'movie',
      genre_ids: [27],
      popularity: 299.839,
      release_date: '2022-10-10',
      video: false,
      vote_average: 6.253,
      vote_count: 93,
    },
    {
      adult: false,
      backdrop_path: '/iiaU8m4kUyDnbqtlr2hyiXYUlcH.jpg',
      id: 723419,
      title: "Mr. Harrigan's Phone",
      original_language: 'en',
      original_title: "Mr. Harrigan's Phone",
      overview:
        'Craig, a young boy living in a small town befriends an older, reclusive billionaire, Mr. Harrigan. The two form a bond over books and an iPhone, but when the man passes away the boy discovers that not everything dead is gone.',
      poster_path: '/gPn9e8eP7TeKQU4IeWAMzOajR40.jpg',
      media_type: 'movie',
      genre_ids: [53, 18, 27],
      popularity: 1259.945,
      release_date: '2022-10-05',
      video: false,
      vote_average: 6.7,
      vote_count: 270,
    },
    {
      adult: false,
      backdrop_path: '/cuAUhb0aYQ9PsdU7EN3L2p1d3Ox.jpg',
      id: 864959,
      title: 'The Curse of Bridge Hollow',
      original_language: 'en',
      original_title: 'The Curse of Bridge Hollow',
      overview:
        "A Halloween-hating dad reluctantly teams up with his teenage daughter when an evil spirit wreaks havoc by making their town's decorations come to life.",
      poster_path: '/t6P9l6tcVnWLS1ADUAfkUCGQhm0.jpg',
      media_type: 'movie',
      genre_ids: [12, 35, 27],
      popularity: 82.414,
      release_date: '2022-10-14',
      video: false,
      vote_average: 6.979,
      vote_count: 47,
    },
    {
      adult: false,
      backdrop_path: '/s4ZEtO5Lo444WJ5lBVyYARAq08.jpg',
      id: 826769,
      title: 'Rosaline',
      original_language: 'en',
      original_title: 'Rosaline',
      overview:
        "Left heartbroken after Romeo begins to pursue her cousin Juliet, Rosaline schemes to foil the famous romance and win back her guy in this comedic twist of Shakespeare's Romeo and Juliet.",
      poster_path: '/jQHrbzVy6ptopxqUohV6PcmmVcY.jpg',
      media_type: 'movie',
      genre_ids: [35, 10749, 36],
      popularity: 52.154,
      release_date: '2022-10-11',
      video: false,
      vote_average: 7.576,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: '/z8KsgBFtduX5bS1yVkjoGo4L7KJ.jpg',
      id: 597922,
      title: 'The Greatest Beer Run Ever',
      original_language: 'en',
      original_title: 'The Greatest Beer Run Ever',
      overview:
        'Chickie wants to support his friends fighting in Vietnam, so he does something wild—personally bring them American beer. What starts as a well-meaning journey quickly changes Chickie’s life and perspective. Based on a true story.',
      poster_path: '/ggf37TpcKaxwguhvtNn6MQpyqBn.jpg',
      media_type: 'movie',
      genre_ids: [18, 35, 10752],
      popularity: 866.816,
      release_date: '2022-09-30',
      video: false,
      vote_average: 7.804,
      vote_count: 225,
    },
    {
      adult: false,
      backdrop_path: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg',
      id: 436270,
      title: 'Black Adam',
      original_language: 'en',
      original_title: 'Black Adam',
      overview:
        'Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.',
      poster_path: '/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg',
      media_type: 'movie',
      genre_ids: [28, 14, 12],
      popularity: 1364.865,
      release_date: '2022-10-19',
      video: false,
      vote_average: 9.204,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: '/2k9tBql5GYH328Krj66tDT9LtFZ.jpg',
      id: 760741,
      title: 'Beast',
      original_language: 'en',
      original_title: 'Beast',
      overview:
        'A recently widowed man and his two teenage daughters travel to a game reserve in South Africa. However, their journey of healing soon turns into a fight for survival when a bloodthirsty lion starts to stalk them.',
      poster_path: '/asRkNwbMuLheJ2nnnbRCIr2PdnI.jpg',
      media_type: 'movie',
      genre_ids: [53, 12, 27],
      popularity: 1644.547,
      release_date: '2022-08-11',
      video: false,
      vote_average: 7.018,
      vote_count: 653,
    },
    {
      adult: false,
      backdrop_path: '/olPXihyFeeNvnaD6IOBltgIV1FU.jpg',
      id: 882598,
      title: 'Smile',
      original_language: 'en',
      original_title: 'Smile',
      overview:
        "After witnessing a bizarre, traumatic incident involving a patient, Dr. Rose Cotter starts experiencing frightening occurrences that she can't explain. As an overwhelming terror begins taking over her life, Rose must confront her troubling past in order to survive and escape her horrifying new reality.",
      poster_path: '/aPqcQwu4VGEewPhagWNncDbJ9Xp.jpg',
      media_type: 'movie',
      genre_ids: [27, 9648],
      popularity: 1458.883,
      release_date: '2022-09-23',
      video: false,
      vote_average: 6.764,
      vote_count: 216,
    },
    {
      adult: false,
      backdrop_path: '/whn480SyRnaHxYqZlKR4COASykD.jpg',
      id: 635891,
      title: 'Clerks III',
      original_language: 'en',
      original_title: 'Clerks III',
      overview:
        'After narrowly surviving a massive heart attack, Randal enlists his old friend Dante to help him make a movie immortalizing their youthful days at the little convenience store that started it all.',
      poster_path: '/apzIqZIQLc8fNx5nbbcSSfPFtax.jpg',
      media_type: 'movie',
      genre_ids: [35],
      popularity: 22.372,
      release_date: '2022-09-04',
      video: false,
      vote_average: 7.047,
      vote_count: 32,
    },
    {
      adult: false,
      backdrop_path: '/tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg',
      id: 717728,
      title: 'Jeepers Creepers: Reborn',
      original_language: 'en',
      original_title: 'Jeepers Creepers: Reborn',
      overview:
        'Forced to travel with her boyfriend to a horror festival, Laine begins to experience disturbing visions associated with the urban legend of The Creeper. As the festival arrives and the blood-soaked entertainment builds to a frenzy, she becomes the center of it while something unearthly has been summoned.',
      poster_path: '/aGBuiirBIQ7o64FmJxO53eYDuro.jpg',
      media_type: 'movie',
      genre_ids: [27, 53, 9648],
      popularity: 546.321,
      release_date: '2022-09-15',
      video: false,
      vote_average: 5.823,
      vote_count: 254,
    },
    {
      adult: false,
      backdrop_path: '/v5alGCugC2HSJtZhH3L01nUPKXZ.jpg',
      id: 759507,
      title: 'Blackout',
      original_language: 'en',
      original_title: 'Blackout',
      overview:
        'A man wakes in a hospital with no memory, and quickly finds himself on the run in a locked down hospital with the Cartel on his tail.',
      poster_path: '/xDgnmbdWS59NtTPdzujdZGuPUPZ.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 53],
      popularity: 204.996,
      release_date: '2022-10-12',
      video: false,
      vote_average: 5.938,
      vote_count: 24,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
